services:
  - type: web
    name: habit-tracker-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habit-tracker-db
          property: connectionString
      - key: NODE_ENV
        value: production